language: node_js
node_js:
    - "6"
script:
    - npm run coverage
    - npm run it
after_success:
    - test $TRAVIS_BRANCH = "master" && npm run coveralls
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/19547337979e0c84f48d
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
